replicaCount: 1
image:
  repository: gcr.io/zens-main/scheduler
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  kafkaHost: operated-kafka2-kafka-bootstrap.kafka.svc.cluster.local:9092
  idempotenceStoreUrl: "svc-idempotence-store-idempotence-store"
